name: Build, Test, and Publish

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install 
      - name: Run tests
        run: |
          poetry run pytest tests/  # Runs the test suite

      - name: Build package
        run: |
          poetry build  # Builds the package

      - name: Publish to TestPyPI
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $TEST_PYPI_API_TOKEN
          poetry publish -r testpypi
